"""empty message

Revision ID: 5025a919e8ee
Revises: b86a070f0ec2
Create Date: 2022-05-11 07:32:30.908698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5025a919e8ee'
down_revision = 'b86a070f0ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compatible', sa.Column('create_by', sa.String(), nullable=True))
    op.create_foreign_key('fk_compatible_create_by', 'compatible', 'userinfo', ['create_by'], ['username'])
    op.drop_column('compatible', 'dateModified')
    op.alter_column('compatible', 'dateCreated', new_column_name='date_created')
    op.execute("UPDATE compatible SET create_by = 'chang' WHERE create_by IS NULL;")
    op.alter_column('compatible', 'create_by', nullable=False)

    op.alter_column('component', 'dateCreated', new_column_name='date_created')
    op.alter_column('component', 'dateModified', new_column_name='date_modified')
    op.alter_column('component', 'componentType', new_column_name='component_type')

    op.add_column('component', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('component', sa.Column('modify_by', sa.String(), nullable=True))
    op.create_foreign_key('fk_component_create_by', 'component', 'userinfo', ['create_by'], ['username'])
    op.create_foreign_key('fk_component_modify_by', 'component', 'userinfo', ['modify_by'], ['username'])
    op.execute("UPDATE component SET create_by = 'chang' WHERE create_by IS NULL;")
    op.alter_column('component', 'create_by', nullable=False)
    op.execute("UPDATE component SET create_by = 'chang' WHERE create_by IS NULL;")
    op.alter_column('component', 'create_by', nullable=False)

    op.alter_column('motherboard', 'dateCreated', new_column_name='date_created')
    op.alter_column('motherboard', 'dateModified', new_column_name='date_modified')

    op.add_column('motherboard', sa.Column('create_by', sa.String(), nullable=True))
    op.add_column('motherboard', sa.Column('modify_by', sa.String(), nullable=True))
    op.create_foreign_key('fk_motherboard_create_by', 'motherboard', 'userinfo', ['create_by'], ['username'])
    op.create_foreign_key('fk_motherboard_modify_by', 'motherboard', 'userinfo', ['modify_by'], ['username'])
    op.execute("UPDATE motherboard SET create_by = 'chang' WHERE create_by IS NULL;")
    op.alter_column('motherboard', 'create_by', nullable=False)
    op.execute("UPDATE motherboard SET create_by = 'chang' WHERE create_by IS NULL;")
    op.alter_column('motherboard', 'create_by', nullable=False)

    op.alter_column('userinfo', 'dateCreated', new_column_name='date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userinfo', 'date_created', new_column_name='dateCreated')
    
    op.alter_column('motherboard', 'date_created', new_column_name='dateCreated')
    op.alter_column('motherboard', 'date_modified', new_column_name='dateModified')
    op.drop_constraint('fk_motherboard_create_by', 'motherboard', type_='foreignkey')
    op.drop_constraint('fk_motherboard_modify_by', 'motherboard', type_='foreignkey')
    op.drop_column('motherboard', 'modify_by')
    op.drop_column('motherboard', 'create_by')

    op.alter_column('component', 'date_created', new_column_name='dateCreated')
    op.alter_column('component', 'date_modified', new_column_name='dateModified')
    op.alter_column('component', 'component_type', new_column_name='componentType')
    op.drop_constraint('fk_component_create_by', 'component', type_='foreignkey')
    op.drop_constraint('fk_component_modify_by', 'component', type_='foreignkey')
    op.drop_column('component', 'modify_by')
    op.drop_column('component', 'create_by')

    op.add_column('compatible', sa.Column('date_modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.execute("UPDATE compatible SET date_modified = NOW() WHERE date_modified IS NULL;")
    op.alter_column('compatible', 'date_modified', new_column_name='dateModified', nullable=False)

    op.drop_constraint('fk_compatible_create_by', 'compatible', type_='foreignkey')
    op.drop_column('compatible', 'create_by')
    op.alter_column('compatible', 'date_created', new_column_name='dateCreated')
    # ### end Alembic commands ###
