"""empty message

Revision ID: 9484001858c1
Revises: ad0eaff339a0
Create Date: 2022-05-24 23:23:57.633974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9484001858c1'
down_revision = 'ad0eaff339a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_motherboard', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('create_by', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['create_by'], ['userinfo.id'], ),
    sa.ForeignKeyConstraint(['id_motherboard'], ['motherboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_components',
    sa.Column('id_simulation', sa.Integer(), nullable=False),
    sa.Column('id_component', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_component'], ['component.id'], ),
    sa.ForeignKeyConstraint(['id_simulation'], ['simulation.id'], ),
    sa.PrimaryKeyConstraint('id_simulation', 'id_component')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_components')
    op.drop_table('simulation')
    # ### end Alembic commands ###
