"""empty message

Revision ID: 9c17835c96fa
Revises: d199b92a8a95
Create Date: 2022-05-06 14:49:25.919684

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9c17835c96fa'
down_revision = 'd199b92a8a95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.rename_table('user', 'userinfo')
    op.add_column('userinfo', sa.Column('dateCreated', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('userinfo', 'dateCreated')
    op.rename_table('userinfo', 'user')

    # ### end Alembic commands ###
