"""empty message

Revision ID: ad0eaff339a0
Revises: 5025a919e8ee
Create Date: 2022-05-12 22:20:19.720392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad0eaff339a0'
down_revision = '5025a919e8ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'motherboard', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motherboard', type_='unique')
    # ### end Alembic commands ###
