"""empty message

Revision ID: b221481f7ab6
Revises: b86a070f0ec2
Create Date: 2022-05-10 22:38:30.082848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b221481f7ab6'
down_revision = 'b86a070f0ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compatible', sa.Column('createBy', sa.String(), nullable=False))
    op.create_foreign_key(None, 'compatible', 'userinfo', ['createBy'], ['username'])
    op.drop_column('compatible', 'dateModified')
    op.add_column('component', sa.Column('createBy', sa.String(), nullable=False))
    op.add_column('component', sa.Column('modifyBy', sa.String(), nullable=False))
    op.create_foreign_key(None, 'component', 'userinfo', ['createBy'], ['username'])
    op.create_foreign_key(None, 'component', 'userinfo', ['modifyBy'], ['username'])
    op.add_column('motherboard', sa.Column('createBy', sa.String(), nullable=False))
    op.add_column('motherboard', sa.Column('modifyBy', sa.String(), nullable=False))
    op.create_foreign_key(None, 'motherboard', 'userinfo', ['createBy'], ['username'])
    op.create_foreign_key(None, 'motherboard', 'userinfo', ['modifyBy'], ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'motherboard', type_='foreignkey')
    op.drop_constraint(None, 'motherboard', type_='foreignkey')
    op.drop_column('motherboard', 'modifyBy')
    op.drop_column('motherboard', 'createBy')
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_constraint(None, 'component', type_='foreignkey')
    op.drop_column('component', 'modifyBy')
    op.drop_column('component', 'createBy')
    op.add_column('compatible', sa.Column('dateModified', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'compatible', type_='foreignkey')
    op.drop_column('compatible', 'createBy')
    # ### end Alembic commands ###
