"""empty message

Revision ID: b86a070f0ec2
Revises: 72174f753f04
Create Date: 2022-05-08 09:28:02.688408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b86a070f0ec2'
down_revision = '72174f753f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_component_name', 'component', ['name'])
    op.create_unique_constraint('unique_motherboard_name', 'motherboard', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_motherboard_name', 'motherboard', type_='unique')
    op.drop_constraint('unique_component_name', 'component', type_='unique')
    # ### end Alembic commands ###
