"""empty message

Revision ID: cfa308301c03
Revises: 9c17835c96fa
Create Date: 2022-05-07 23:34:24.085648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa308301c03'
down_revision = '9c17835c96fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatible',
    sa.Column('id_motherboard', sa.Integer(), nullable=False),
    sa.Column('id_component', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_component'], ['component.id'], ),
    sa.ForeignKeyConstraint(['id_motherboard'], ['motherboard.id'], ),
    sa.PrimaryKeyConstraint('id_motherboard', 'id_component')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compatible')
    # ### end Alembic commands ###
